---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: &app cluster-apps-atuin
  namespace: flux-system
  labels:
    substitution.flux.home.arpa/enabled: "true"
spec:
  targetNamespace: default
  suspend: false
  dependsOn:
    - name: onepassword
      namespace: external-secrets
    - name: external-secrets
      namespace: external-secrets
  path: ./kubernetes/apps/default/atuin/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  interval: 30m
  retryInterval: 1m
  timeout: 3m
