# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cloudflared-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:6GoVXDibdCnils8wKsgvmb8CknDRg9ADbYcPVqL42sjQE1rnGfqPFu25S3a73Rpju4w6QCsRQ+gJY1QlzP3P8XdrYUSCdTPHo5QWGZpIAOhwWN/iHjeq+6Uy3DoPCq09WKtdms6pzwv4jYZRLIxGdjFESlIl7M9SOj4qVXoEFoe0Kq/cb1A064oagJE3+eecyfvle7RSO2BLpiWq6dnsHrR+yvQhG2BUnJ23FdnGYn+8L6zVGA==,iv:PhDuMh1ynibGTgY+DvhFAPN2vmA78t9ROLuJMZDc5Ko=,tag:Rw4s1N5kEiwqoyuZnO4whQ==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age103nuugystdqulejsqxx98t9ju8l2ltmsmtx3q60nw5jr5p6jgvzs4gtp9t
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4VGhkck9ZTm8zeEd3OTZU
        SU1sZDdNd01mNTc0MGVwaFM4Q28xVUVMRmtrCm9tNkZYRVNJOFNWTHVraHNITVlS
        eVh6WUJINmFKUE4wZGMyQ0MrSEN0NlEKLS0tIFhuT2p2elJacC9SOUVJSlk1TVRR
        dXp3K2NmUy9QSzRYMnNqTnUxS0hhQzQKz/XZ2QpU7jldGF/XlRl1TdK1VyYsc4li
        Gs7HVdnxaGbftGKcBFEH6h0K9NFg6VbMP9vCgThSn7/VssqjRxY9PA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-04-04T05:08:24Z"
  mac: ENC[AES256_GCM,data:Ks4XEXlC5UsioltnPJDGKQxFG25htR70VrtdGi4gP7YQmVU9CHZbTJ10iWpGJnuS8FmyvVNCxbcrRFdBQIlgeu3ZzOkpuASTG0PS2aU9s+1yD+VJzT8SnwP4kj4P9nSIy2J4DFWOpPUYY6XS2OVaItuRMfnOJxrNW5XsoqAr/T8=,iv:hTV7kk2yOAxf6U8E2NhuIYShtP3lCOJvIRlz/LydiZQ=,tag:pyzpO8Uz/mA1NHNvsYKelQ==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
