# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: external-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:j1bpDmoH1JBMFG70IZ0qf3gms5rEyLvxN5jrPwv/pSMVzx4+7xMHSA==,iv:j30rjbGRQlAwjslh7EnWyrBIgNdqCrTO/Bmp4bWRgDU=,tag:4DCso8EOe+bv/0ke2+ktAg==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age103nuugystdqulejsqxx98t9ju8l2ltmsmtx3q60nw5jr5p6jgvzs4gtp9t
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRbmNEK0c0eDdCYmQ3MXd2
        Q1pPbXpWbjRrTEVOSjJXSGF0TGdENC8xUUZBCmdLanBablA4dmtEWktCV0lqRUxW
        dVBmYjVtb2s2dTRkT002aHZIcS85Yk0KLS0tIEZ6TTVJdkt3c0puSS8xRnM2aHRh
        QzB6ZmVDL0UxOE5QT2xpa0JUczdkcUEKtEt+hr5jrpR3cxhBGGZpA87j/k0o0WFB
        lLbr0X0dJPo4+Ap+SiulHyLi3QD4VS+8bHLIVjvZUyiVZSUZQhx9oQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-04-04T05:08:24Z"
  mac: ENC[AES256_GCM,data:WU5B6+i3BvXX7xhsunK0x1j8zXd94jiGK/y6XiirwYvCOOV57rloikjXrbQ2Uxd3/0y3EHrsrEN7VaPmPsFIa5voYBXCdo2EveBB8RI4K27pp+dVkVoFX7nq60otqXtNcexeKPAVa+nepUsRXOYOaROuOpM1gKLkO92qK1R0j04=,iv:QTu8tMydGK6iQtzqCIzfDZrkHbfx918TeO8sYIMLCXg=,tag:aSdbIMeZFDHCWkTqf8e5Rw==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
