# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:XjHAPOQl87soWXQ8y6Q8qmA1LSS8SQABiUoclD6UDBo=,iv:TlR5QPQOYeej4+MTSv6/+U2p6muKDCUiOzi+tWnnOxI=,tag:Dwsb60Icn9ukECWtnoHKYQ==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age103nuugystdqulejsqxx98t9ju8l2ltmsmtx3q60nw5jr5p6jgvzs4gtp9t
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5R3ZORlBvM1VPT1g4YWx4
        ajhxOE91YkJBN3NrWnNmcno5ekFlSzZpeURzCnI4UlhTdzZ6aVQ0Ny9jQkFLbkdS
        QmNKL05PcW16WUtzZk5lVkJ3dlBtZTQKLS0tIE1SQVpXT2I3dXhrd2Y5ejZBeU9C
        RkNpcSsyU3pLRFhSeHNFMUlvTTNDSUUKM5bqZWsQCPttrjpopNmrIpUhdLN0NW5m
        zE6UMAc2viupO474azMnKQ3nzwFunpkhHEeeEcaPvyKLglgiGHzOgg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-04-04T05:08:24Z"
  mac: ENC[AES256_GCM,data:TvgeHcUgO9tAUF8h2aF9w7+9+lSVw+wmNB4DsxV2X7RqQpr5MH7N0+olbypU9Y/sZPTV4wk3OkPh//qrBx9OIPx6lE1g58ZYknb5OkQ0ddi41nvPh6VGdaNiHGv6j7pyE30zNlNzqJcY6O9iHH0gDCji1tkJDMOyLyC5ZDZxUgU=,iv:thtJrvsGFMKF3KyDOthXdZQX8wHu8ZQG0tCtONgmxA4=,tag:uGF/J6POiDKTijVXQwCUfQ==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
