apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:XGhUrRNyzP/7rY4ZkzHx,iv:b6gUAJ/bl3adg8Rvc/C5LKexQZw+mGxD7316YYZdiw4=,tag:4ohEdXF8KEKcheD97Zj/Yw==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age103nuugystdqulejsqxx98t9ju8l2ltmsmtx3q60nw5jr5p6jgvzs4gtp9t
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQb3pmbCs3dFNESFg1RVpx
        a1kzdTJFZWNha3l3N1Nvb3RGeG16RGkwU3dzClk2WHJuZHVTVi9TUk5oZGgzWXZq
        MmR0S2c3MHUwdkpRRjdKRDNFazdjeTAKLS0tIGZSek9Wbk1MNFByK3V6ZUd4RXlD
        bHArWGVoM1d2cE9MYTh3L2lRRGgvTk0KrU5Eh8XjXlWrbHZkm0IJDsHOBp0Y08cB
        MNb9oJuRz6kcYPbID+Ic+Zg6nSHNwftj1Vqc1RTapapoXifoiYO2OQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-04-04T05:08:24Z"
  mac: ENC[AES256_GCM,data:19ck1YzPBKPZT1zTX3REEhPlu4zTsgq/pWE/2I2w1IaBcGxLSMVkHX7a3bgk4O+Cmi2bihCVHHZwvuvgutGBGOg259BO3uLITi9bvuup+CXHuTP/OOzmc7wCnu64EcneC0FPphHu6j4nRMw7uHkXoQoOucoGae0xc1EDEuJZ884=,iv:HyDub7sRTyCJ4EZpdfT9DdEaFmAhrGzuz1ORee+iS9w=,tag:+cIYyd0M12VpVHIIpN1CKQ==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
