# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:57ZxcxqmmUPTP30w71+AFMKHUoEN296ZEP57wdIC0Iwo4xlbWtRLqg==,iv:ohdOzf6//V+sGXVldfgW7HYxIav+ef5rTWlC81KTrgQ=,tag:Vdvz/HBguTDyUraxLpqyKQ==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age103nuugystdqulejsqxx98t9ju8l2ltmsmtx3q60nw5jr5p6jgvzs4gtp9t
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWSzJvakZtbzFWeThMVnVw
        K25pWi8yYkJyMldUeVZ2bXUvSkZnbTFHeWtNCjhaZmlJc0l2d3UxMjNOMlpCTmNC
        U09YVjhvdUtNa2M1U25Kb0VDVjI0bkkKLS0tIDhuUWx4R2hxTi8rZEYwcmtVS0ZZ
        UFRTSEg2cjVnMGZBL2lVdnJ5Z3dGaEUKxMFtHhV+5EeMwfTK9PwaF7bDAQSP54A7
        pyEfYvew8J1gL3SNWf1M6VZM87joALj0alU2vHQf9hQLNVtOVn/kAw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-04-04T05:08:24Z"
  mac: ENC[AES256_GCM,data:ZO6dUC34QOjRIRo7AeHqOcUUD8glq+W2JvCRNyIKMekdpwN31jenGWYQ98TxRSkyzYUQY4oSv3AsYnFGtcN6XY0marFpvo0LZ6dapDa1FROJ9sEQWEDWH52n4Cq+rwPvAh6d/s6xqzQSSggwNX5MbYOKnkWai+UIDU0EuQpleiA=,iv:pbl+66tKvbH7fOQCc6ptGDiTOZn+Pry9a8sBJ1HlcO4=,tag:myVcDnEu7eTL1bmky/rLhw==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
