---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrepository-source-v1beta2.json
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: silence-operator-crds
  namespace: flux-system
spec:
  interval: 12h
  type: oci
  url: oci://ghcr.io/home-operations/charts-mirror/silence-operator-crds
