---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: metube-output
spec:
  storageClassName: openebs-hostpath
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 10Gi
