---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: lubelog-pvc-v1
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: openebs-hostpath
